---
apiVersion: v1
kind: Secret
metadata:
  name: volume-azurefile-storage-secret
type: Opaque
data:
  azurestorageaccountname: a2FsZGltb2RlbA==
  azurestorageaccountkey: UkdqL00yU0xjNXd0T05qZUxlVFFORU1SbUJZeCs2MTRRbC9oTGVHenFFb3J0VkE4UzNJd0M1emIrSmtrNWtPcjFZZ3RUTG8ydUNEVHM1SGJncFFiT0E9PQ==
