---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.0.10.154
    path: "/"
