apiVersion: batch/v1
kind: Job
metadata:
  name: job-worker-for-testing-only
  namespace: speechlab-aks-prod-online
  labels:
    role: speechlab-aks-prod-online-workers-pods
spec:
  template:
    metadata:
      name: job-wq-2
      namespace: speechlab-aks-prod-online
    spec:
      imagePullSecrets:
        - name: azure-cr-secret

      # volumes:
      # - name: models
      #   flexVolume:
      #     driver: "azure/blobfuse"
      #     readOnly: false
      #     secretRef:
      #       name: blobfusecreds
      #     options:
      #       container: CONTAINER-NAME
      #       tmppath: /tmp/onlinespeechlabtestblobfuse
      #       mountoptions: "--file-cache-timeout-in-seconds=120"

      containers:
      - name: c
        image: kalditest.azurecr.io/speechlab-online-scaled
        envFrom:
          - secretRef:
              name: environment-variables-workers-secret
        # volumeMounts:
        # - name: models
        #   mountPath: /home/appuser/opt/models

        # command: ["/opt/start_worker.sh", "-m", "speechlab-online-master", "-y", "/opt/models/gstream-online2/engine.yaml"]
        command: ["/home/appuser/opt/tini", "--", "/home/appuser/opt/start_worker.sh"]
    
        # ports:
        #     - name: http
        #       containerPort: 8080
        #       protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: "4Gi"
          requests:
            cpu: 1
            memory: "4Gi"

        env:
           - name: RUN_FREQ
             value: ONCE

        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
             add: ["SYS_ADMIN"]


      restartPolicy: OnFailure

