apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-blobfuse
  namespace: speechlab-test
spec:
  containers:
  - name: nginx-flex-blobfuse
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
  - name: test
    flexVolume:
      driver: "azure/blobfuse"
      readOnly: false
      secretRef:
        name: blobfusecreds
      options:
        container: gstream-models
        tmppath: /tmp/blobfuse
        mountoptions: "--file-cache-timeout-in-seconds=120"
