apiVersion: v1
kind: Service
metadata:
  annotations: {
    prometheus.io/scrape: 'true'
  }
  labels:
    app: prometheus-service
  name: prometheus-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: prometheus
  type: ClusterIP