---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-test
spec:
  replicas: 1
  selector:
    role: nfs-test
  template:
    metadata:
      labels:
        role: nfs-test
    spec:
      containers:
      - name: nfs-test
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: pvc-model
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
