models:
  SingaporeEnglish_0519NNET3: 1  
  SingaporeCS_0519NNET3: 1
  SingaporeMandarin_0519NNET3: 0
  
image:
  repository: kalditest.azurecr.io/kalditestscaled
  tag: latest
  pullPolicy: Always
  pullSecrets: azure-cr-secret

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  #type: LoadBalancer
  port: 8080
  resourceGroup: kaldi-test


  #loadBalancerIP: 137.116.136.155 # onlinespeechlabtest.southeastasia.cloudapp.azure.com
  #loadBalancerIP: 13.76.89.12 # speechlab-online.southeastasia.cloudapp.azure.com
  #loadBalancerIP: 20.43.169.228
  enablehttps: false

# resources:
#   worker:
#     limits:
#       memory: "4Gi"
#     requests:
#       memory: "2Gi"

# volumes:
#   name: speechlab-pv-nfs0001
#   claim: speechlab-pvc-nfs0001
#   mount:
#     name: speechlab-vol
#     path: "/opt/models"
#   nfs:
#     path: "/speechlab/models"
#     server: 10.107.19.180
#   capacity:
#     storage: 10Gi

commands:
  master:
    - '"/home/appuser/opt/tini"' 
    - '"--"'
    - '"/home/appuser/opt/start_master.sh"'
    # - '"-y"'
    # - '"/home/appuser/opt/models/engine.yaml"'
  worker:
  # see _helpers.tpl on how full command constructed
    pre:
      - '"/home/appuser/opt/tini"' 
      - '"--"'
      - '"/home/appuser/opt/start_worker.sh"'
      # - '"-m"'
      # - '"speechlab-online-master"'
      
  
    # post:
    #   - '"-y"'
    #   - '"/home/appuser/opt/models/engine.yaml"'
    

