apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-workers-secret
  namespace: kaldi-test
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: kalditeststorage
  AZURE_STORAGE_ACCESS_KEY: lgVCwxAMIfI72/TFcj66N5+dHf1kO8cwglVz/GO4CJJZYQ2RoNazXYFlTdHCMR17c1JXfxBf2I5c4vAZ3J92Zw==
  AZURE_CONTAINER: online-models
  MASTER: speechlab-online-master
  NAMESPACE: kaldi-test
  RUN_FREQ: FOREVER # for run_worker.yaml (testing) will override this with value=ONCE
  ENABLE_HTTPS: "false"


---

apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-master-secret
  namespace: kaldi-test
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: kalditeststorage
  AZURE_STORAGE_ACCESS_KEY: lgVCwxAMIfI72/TFcj66N5+dHf1kO8cwglVz/GO4CJJZYQ2RoNazXYFlTdHCMR17c1JXfxBf2I5c4vAZ3J92Zw==
  AZURE_CONTAINER: online-models
  NAMESPACE: kaldi-test
  MASTER: speechlab-online-master
  ENABLE_HTTPS: "false"