apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-workers-secret
  namespace: kaldi-test
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: kalditeststorage
  AZURE_STORAGE_ACCESS_KEY: EPMFPmsDV4WhoxsIH5C0yJV6YnxnJ4TxdZilOi0s3QJusJOLDaKx3q6UlF/OD0453QGKRDFa7hiZPSevW6qZyw==
  AZURE_CONTAINER: online-models
  MASTER: kaldi-feature-test-master
  NAMESPACE: kaldi-test
  RUN_FREQ: FOREVER # for run_worker.yaml (testing) will override this with value=ONCE
  ENABLE_HTTPS: "false"
  MODELS_FILESHARE_SECRET: models-files-secret
  MODELS_SHARE_NAME: online-models


---

apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-master-secret
  namespace: kaldi-test
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: kalditeststorage
  AZURE_STORAGE_ACCESS_KEY: EPMFPmsDV4WhoxsIH5C0yJV6YnxnJ4TxdZilOi0s3QJusJOLDaKx3q6UlF/OD0453QGKRDFa7hiZPSevW6qZyw==
  AZURE_CONTAINER: online-models
  NAMESPACE: kaldi-test
  MASTER: kaldi-feature-test-master
  ENABLE_HTTPS: "false"
  MODELS_FILESHARE_SECRET: models-files-secret
  MODELS_SHARE_NAME: online-models